# Default values for backoffice-client.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: ittaxi

labels:
  app: backoffice-client
  version: "1"
annotations:
  argocd.argoproj.io/sync-wave: 5


strategy: {}
replicaCount: 1


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


multiaz: 
  enabled: false
