apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backoffice-client.fullname" . }}-secrets
data:
   REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.secrets.googleKey | b64enc }}
   tst : {{ .Values.secrets.dev | b64enc }}
type: Opaque